# ============================================
# SECRET - Datos SENSIBLES
# ============================================
apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
  namespace: product-service
  labels:
    app: product-service

type: Opaque

# Valores codificados en base64 (m√°s seguro que stringData)
data:
  DB_USERNAME: cG9zdGdyZXM=                                          # postgres
  DB_PASSWORD: cG9zdGdyZXM=                                          # postgres
  JWT_SECRET: bTFTM2NyM3RLM3lKV1RfVDNjc3VwMjAyNSFAI1NlY3VyZVRva2Vu  # Misma clave que user-service para validar tokens