# ============================================
# SECRET - Datos SENSIBLES
# ============================================
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: user-service
  labels:
    app: user-service

type: Opaque

# Valores codificados en base64 (m√°s seguro que stringData)                          # CAMBIOS
data:
  DB_USERNAME: cG9zdGdyZXM=                                          # postgres
  DB_PASSWORD: cG9zdGdyZXM=                                          # postgres
  JWT_SECRET: bTFTM2NyM3RLM3lKV1RfVDNjc3VwMjAyNSFAI1NlY3VyZVRva2Vu  # m1S3cr3tK3yJWT_T3csup2025!@#SecureToken