# ============================================
# SERVICE - Exposición de red
# ============================================
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: user-service
  labels:
    app: user-service

spec:
  # ========================================
  # Tipo de Service
  # ========================================
  type: NodePort

  # ========================================
  # Selector: ¿A qué pods dirigir tráfico?
  # ========================================
  selector:
    app: user-service

  # ========================================
  # Puertos
  # ========================================
  ports:
    - name: http
      protocol: TCP

      # port: Puerto del SERVICE (interno)
      port: 80

      # targetPort: Puerto del CONTENEDOR
      targetPort: 8081

      # nodePort: Puerto en LOCALHOST
      # Rango: 30000-32767
      nodePort: 30081
